### ISSUE TITLE
couldnt get it to work on odessey update 15

### ISSUE THREAD

**Issue by PyronoxO** [mmseng/AislingMatHelper#2]
everytime i try to use it, i get the message power contact not available after pressing confirm, any idea ?

**Comment by mmseng** [comment]
Check out the documentation in the readme about the [DelayLoadItemsMultiplierAdjustmentMultiplier](https://github.com/mmseng/AislingMatHelper#delayloaditemsmultiplieradjustmentmultiplier) and [DelayLoadUnload](https://github.com/mmseng/AislingMatHelper#delayloadunload) timing variables, and try tweaking them as prescribed.

I haven't played in a while so this script is untested (by me) on the newest versions of the game, but that error in particular is a known quantity, and these delay variables are there to help avoid it. The documentation also notes how to recover from the error.

**Comment by mmseng** [comment]
Closing until further response.
